package xyz.trankvila.menteia.datumo

import xyz.trankvila.menteia.tipsistemo.*

object VeteraDatumo {
    val lokoj = mapOf("sitana" to 6176823)
    val kodoj = mapOf(
            200 to "divis sakini mino saleri",
            201 to "divis sakini saleri",
            202 to "divis sakini trisa saleri",
            210 to "mino sakini",
            211 to "sakini",
            212 to "trisa sakini",
            221 to "pabupi sakisi",
            230 to "divis sakini mino saremi",
            231 to "divis sakini saremi",
            232 to "divis sakini trisa saremi",

            300 to "mino saremi",
            301 to "saremi",
            302 to "trisa saremi",
            310 to "mino saremi", // light intensity drizzle rain
            311 to "saremi", // drizzle rain
            312 to "trisa saremi", // heavy intensity drizzle rain
            313 to "divis salena saremi",
            314 to "trisa divis salena saremi",
            321 to "salena", // shower drizzle

            500 to "mino saleri",
            501 to "druva saleri",
            502 to "trisa saleri",
            503 to "trisa saleri", // very heavy rain
            504 to "kitri saleri",
            511 to "sikreri",
            520 to "mino saleni saleri",
            521 to "saleni saleri",
            522 to "trisa saleni saleri",
            531 to "pabupi saleni saleri",

            600 to "mino varumi",
            601 to "varumi",
            602 to "trisa varumi",
            611 to "salekres",
            612 to "saleni salekres",
            615 to "mino divis saleri varumi",
            616 to "divis saleri varumi",
            620 to "mino saleni varumi",
            621 to "saleni varumi",
            622 to "trisa saleni varumi",

            701 to "furema",
            711 to "plesuta",
            721 to "plemuna",
            731 to "gletami",
            741 to "murena",
            751 to "gletami", // sand
            761 to "gletami", // dust
            762 to "kuriska",
            771 to "ferisa",
            781 to "klitepa",

            800 to "ʃanare",
            801 to "mino molaro",
            802 to "neda molaro",
            803 to "lisa molaro",
            804 to "molaro"
    )

    val hereKodoj = mapOf(
            "sunny" to ŝanare(),
            "clear" to ŝanare(),
            "mostly_sunny" to lisa(ŝanare()),
            "mostly_clear" to lisa(ŝanare()),
            "passing_clouds" to mino(molaro()),
            "more_sun_than_clouds" to mino(molaro()),
            "scattered_clouds" to mino(molaro()),
            "partly_cloudy" to neda(molaro()),
            "a_mixture_of_sun_and_clouds" to neda(molaro()),
            "increasing_cloudiness" to lisa(molaro()),
            "breaks_of_sun_late" to lisa(molaro()),
            "afternoon_clouds" to neda(molaro()),
            "morning_clouds" to neda(molaro()),
            "partly_sunny" to neda(ŝanare()),
            "high_level_clouds" to neda(molaro()),
            "decreasing_cloudiness" to mino(molaro()),
            "clearing_skies" to lisa(ŝanare()),
            "high_clouds" to neda(molaro()),
            "rain_early" to saleri(),
            "heavy_rain_early" to trisa(saleri()),
            "strong_thunderstorms" to trisa(sakini()),
            "severe_thunderstorms" to kitri(sakini()),
            "thundershowers" to saleni(sakini()),
            "thunderstorms" to sakini(),
            "tstorms_early" to sakini(),
            "isolated_tstorms_late" to pabupi(sakini()),
            "scattered_tstorms_late" to pabupi(sakini()),
            "tstorms_late" to sakini(),
            "tstorms" to sakini(),
            "ice_fog" to furema(),
            "more_clouds_than_sun" to lisa(molaro()),
            "broken_clouds" to mino(molaro()),
            "scattered_showers" to pabupi(salena()),
            "a_few_showers" to mino(salena()),
            "light_showers" to mino(salena()),
            "passing_showers" to mino(salena()),
            "rain_showers" to saleni(saleri()),
            "showers" to salena(),
            "widely_scattered_tshorms" to pabupi(sakini()),
            "isolated_tstorms" to sakini(),
            "a_few_tstorms" to mino(sakini()),
            "scattered_tstorms" to sakini(),
            "hazy_sunshine" to plemuna(),
            "haze" to plemuna(),
            "smoke" to plesuta(),
            "low_level_haze" to plemuna(),
            "early_fog_followed_by_sunny_skies" to mino(plemuna()),
            "early_fog" to murena(),
            "light_fog" to mino(murena()),
            "fog" to murena(),
            "dense_fog" to trisa(murena()),
            "night_haze" to plemuna(),
            "night_smoke" to plesuta(),
            "night_low_level_haze" to plemuna(),
            "night_widely_scattered_tstorms" to sakini(),
            "night_isolated_tstorms" to pabupi(sakini()),
            "night_a_few_tstorms" to mino(sakini()),
            "night_scattered_tstorms" to sakini(),
            "night_tstorms" to sakini(),
            "night_clear" to ŝanare(),
            "mostly_cloudy" to lisa(molaro()),
            "cloudy" to molaro(),
            "overcast" to trisa(molaro()),
            "low_clouds" to neda(molaro()),
            "hail" to plikreda(),
            "sleet" to salekres(),
            "light_mixture_of_precip" to mino(salekres()),
            "icy_mix" to salekres(),
            "mixture_of_precip" to salekres(),
            "heavy_mixture_of_precip" to trisa(salekres()),
            "snow_changing_to_rain" to divis(varumi(), saleri()),
            "snow_changing_to_an_icy_mix" to divis(varumi(), salekres()),
            "an_icy_mix_changing_to_snow" to divis(salekres(), varumi()),
            "an_icy_mix_changing_to_rain" to divis(salekres(), saleri()),
            "rain_changing_to_snow" to divis(saleri(), varumi()),
            "rain_changing_to_an_icy_mix" to divis(saleri(), salekres()),
            "light_icy_mix_early" to mino(salekres()),
            "icy_mix_early" to salekres(),
            "light_icy_mix_late" to mino(salekres()),
            "icy_mix_late" to salekres(),
            "snow_rain_mix" to salekres(),
            "scattered_flurries" to mino(varumi()),
            "snow_flurries" to varumi(),
            "light_snow_showers" to mino(saleni(varumi())),
            "snow_showers" to saleni(varumi()),
            "light_snow" to mino(varumi()),
            "flurries_early" to mino(varumi()),
            "snow_showers_early" to saleni(varumi()),
            "light_snow_early" to mino(varumi()),
            "flurries_late" to mino(varumi()),
            "snow_showers_late" to saleni(varumi()),
            "light_snow_late" to mino(varumi()),
            "night_decreasing_cloudiness" to neda(molaro()),
            "night_clearing_skies" to mino(molaro()),
            "night_high_level_clouds" to molaro(),
            "night_high_clouds" to molaro(),
            "night_scattered_showers" to mino(salena()),
            "night_a_few_showers" to mino(salena()),
            "night_light_showers" to mino(salena()),
            "night_passing_showers" to mino(salena()),
            "night_rain_showers" to saleni(saleri()),
            "night_sprinkles" to salena(),
            "night_showers" to salena(),
            "night_mostly_clear" to lisa(ŝanare()),
            "night_passing_clouds" to mino(molaro()),
            "night_scattered_clouds" to mino(molaro()),
            "night_partly_cloudy" to neda(molaro()),
            "increasing_cloudiness" to lisa(molaro()),
            "night_afternoon_clouds" to molaro(),
            "night_morning_clouds" to molaro(),
            "night_broken_clouds" to pabupi(molaro()),
            "night_mostly_cloudy" to lisa(molaro()),
            "light_freezing_rain" to mino(sikreri()),
            "freezing_rain" to sikreri(),
            "heavy_rain" to trisa(saleri()),
            "lots_of_rain" to trisa(saleri()),
            "tons_of_rain" to kitri(saleri()),
            "heavy_rain_early" to trisa(saleri()),
            "heavy_rain_late" to trisa(saleri()),
            "flash_floods" to kitri(busmisa()),
            "flood" to busmisa(),
            "drizzle" to saremi(),
            "sprinkles" to saremi(),
            "light_rain" to mino(saleri()),
            "sprinkles_early" to saremi(),
            "light_rain_early" to mino(saleri()),
            "sprinkles_late" to saremi(),
            "light_rain_late" to mino(saleri()),
            "rain" to saleri(),
            "numerous_showers" to pabupi(salena()),
            "showery" to salena(),
            "showers_early" to salena(),
            "rain_early" to saleri(),
            "showers_late" to salena(),
            "rain_late" to saleri(),
            "snow" to varumi(),
            "moderate_snow" to druva(varumi()),
            "snow_early" to varumi(),
            "snow_late" to varumi(),
            "heavy_snow" to trisa(varumi()),
            "heavy_snow_early" to trisa(varumi()),
            "heavy_snow_late" to trisa(varumi()),
            "tornado" to klitepa(),
            "tropical_storm" to krispita(),
            "hurricane" to kitri(ferisa()),
            "sandstorm" to kitri(gletami()),
            "duststorm" to kitri(gletami()),
            "snowstorm" to kitri(varumi()),
            "blizzard" to kitri(varumi())
    )
}