package xyz.trankvila.menteia.tipsistemo

import kotlin.reflect.KClass

val tipoj: Map<String, KClass<out timis>> = mapOf(
        "timis" to timis::class,
        "mira" to mira::class,
        "miri" to miri::class,
        "pona" to pona::class,
        "poni" to poni::class,
        "fora" to fora::class,
        "fori" to fora::class,
        "nona" to nona::class,
        "tera" to tera::class,
        "ponega" to ponega::class,
        "noni" to noni::class,
        "teri" to teri::class,
        "sina" to sina::class,
        "sini" to sini::class,
        "lira" to lira::class,
        "liri" to liri::class,
        "ŝona" to ŝona::class,
        "ŝoni" to ŝoni::class,
        "kera" to kera::class,
        "keri" to keri::class,
        "gina" to gina::class,
        "gini" to gini::class,
        "taris" to taris::class,
        "prena" to prena::class,
        "dreta" to dreta::class,
        "glima" to glima::class,
        "sariga" to sariga::class,
        "lemis" to lemis::class,
        "brodimis" to brodimis::class,
        "kiremis" to kiremis::class,
        "kamis" to kamis::class,
        "girimis" to girimis::class,
        "liris" to liris::class,
        "generas" to generas::class,
        "poneras" to poneras::class,
        "prenis" to prenis::class,
        "gulos" to gulos::class,
        "kredas" to kredas::class,
        "ko" to ko::class,
        "fragemis" to vanemis.fragemis::class,
        "to" to to::class,
        "doni" to doni::class
)