package xyz.trankvila.menteia.tipsistemo

import kotlin.reflect.KClass

val vortoj: Map<String, KClass<out timis>> = mapOf(
        "timis" to timis::class,
        "mira" to mira::class,
        "miri" to miri::class,
        "pona" to pona::class,
        "poni" to poni::class,
        "fora" to fora::class,
        "fori" to fori::class,
        "nona" to nona::class,
        "tera" to tera::class,
        "ponega" to ponega::class,
        "noni" to noni::class,
        "teri" to teri::class,
        "sina" to sina::class,
        "sini" to sini::class,
        "lira" to lira::class,
        "liri" to liri::class,
        "ŝona" to ŝona::class,
        "ŝoni" to ŝoni::class,
        "kera" to kera::class,
        "keri" to keri::class,
        "gina" to gina::class,
        "gini" to gini::class,
        "taris" to taris::class,
        "prena" to prena::class,
        "dreta" to dreta::class,
        "glima" to glima::class,
        "sariga" to sariga::class,
        "lemis" to lemis::class,
        "brodimis" to brodimis::class,
        "kiremis" to kiremis::class,
        "kamis" to kamis::class,
        "girimis" to girimis::class,
        "liris" to liris::class,
        "generas" to generas::class,
        "poneras" to poneras::class,
        "prenis" to prenis::class,
        "gulos" to gulos::class,
        "kredas" to kredas::class,
        "ko" to ko::class,
        "fragemis" to vanemis.fragemis::class,
        "to" to to::class,
        "doni" to doni::class,
        "sagi" to sagi::class,
        "negi" to negi::class,
        "pegi" to pegi::class,
        "regi" to regi::class,
        "megi" to megi::class,
        "tres" to tres::class,
        "ŝanare" to ŝanare::class,
        "varumi" to varumi::class,
        "saleri" to saleri::class,
        "salena" to salena::class,
        "saleni" to saleni::class,
        "lisa" to lisa::class,
        "geradas" to geradas::class,
        "lemona" to lemona::class,
        "fidinas" to fidinas::class,
        "karima" to karima::class,
        "fitam" to fitam::class,
        "lurina" to lurina::class,
        "des" to des::class,
        "buve" to buve::class,
        "mave" to mave::class,
        "marisas" to marisas::class,
        "keli" to keli::class,
        "buvi" to buvi::class,
        "mavi" to mavi::class,
        "darena" to darena::class,
        "gemuna" to gemuna::class,
        "valima" to valima::class,
        "sadika" to sadika::class,
        "molaro" to molaro::class,
        "nevum" to nevum::class,
        "saremi" to saremi::class,
        "saresa" to saresa::class,
        "silega" to silega::class,
        "sasigas" to sasigas::class,
        "miris" to miris::class,
        "maraga" to maraga::class,
        "klos" to klos::class
)

val tipoj = mapOf(
        "timis" to timis::class,
        "brodimis" to brodimis::class,
        "girimis" to girimis::class,
        "kamis" to kamis::class,
        "sinemis" to sinemis::class,
        "karimis" to karimis::class,
        "ŝanamis" to ŝanamis::class,
        "milimis" to milimis::class,
        "krumis" to krumis::class,
        "kredimis" to kredimis::class,
        "nomis nevum" to `nomis nevum`::class
)